USE [master]
GO

/****** Object:  Database [PokemonTracker]    Script Date: 8/15/2016 12:14:31 PM ******/
CREATE DATABASE [PokemonTracker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PokemonTracker', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PokemonTracker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PokemonTracker_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PokemonTracker_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PokemonTracker] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PokemonTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PokemonTracker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PokemonTracker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PokemonTracker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PokemonTracker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PokemonTracker] SET ARITHABORT OFF 
GO

ALTER DATABASE [PokemonTracker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PokemonTracker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PokemonTracker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PokemonTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PokemonTracker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PokemonTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PokemonTracker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PokemonTracker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PokemonTracker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PokemonTracker] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PokemonTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PokemonTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PokemonTracker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PokemonTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PokemonTracker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PokemonTracker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PokemonTracker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PokemonTracker] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PokemonTracker] SET  MULTI_USER 
GO

ALTER DATABASE [PokemonTracker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PokemonTracker] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PokemonTracker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PokemonTracker] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PokemonTracker] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PokemonTracker] SET QUERY_STORE = OFF
GO

USE [PokemonTracker]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PokemonTracker] SET  READ_WRITE 
GO

